services:
  user-service:
    build: ./user_service
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - postgres
      - rabbitmq
  
  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - postgres
      - rabbitmq
  
  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:4-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./db-data/rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
